# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [6]:
import pandas as pd
url ="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
dw_pandas = pd.read_csv(url)
display(dw_pandas)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

NameError: name 'jaws' is not defined

NameError: name 'jaws' is not defined

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [2]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

dw_pandas = pd.read_csv(url)

# Display the first five rows
display(dw_pandas.head())

# Display the last five rows
display(dw_pandas.tail())

# Check the original dimensions
print("Dataset dimensions:", dw_pandas.shape)

# Check column names
print("\nColumn names:")
print(dw_pandas.columns.tolist())

# Check data types and missing values
dw_pandas.info()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset dimensions: (4008, 11)

Column names:
['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Income', 'Monthly Premium Auto', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class', 'Total Claim Amount']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [3]:
# Remove completely empty rows
dw_pandas = dw_pandas.dropna(how="all").copy()

# Clean column names
dw_pandas.columns = dw_pandas.columns.str.strip()

# Check duplicate rows
print("Duplicate rows:", dw_pandas.duplicated().sum())

# Remove duplicate rows if any exist
dw_pandas = dw_pandas.drop_duplicates().copy()

# Check the new dimensions
print("Cleaned dimensions:", dw_pandas.shape)

display(dw_pandas.head())

Duplicate rows: 0
Cleaned dimensions: (1071, 11)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [4]:
# Convert Customer Lifetime Value from percentage text to numeric values.
# Example: "697953.59%" becomes 6979.5359
clv = dw_pandas["Customer Lifetime Value"].astype("string").str.strip()

dw_pandas["Customer Lifetime Value"] = pd.to_numeric(
    clv.str.replace("%", "", regex=False),
    errors="coerce"
) / 100

# Convert complaint values such as "1/0/00" to 1.
# Keep this conversion only if inspection confirms the first number
# represents the original complaint count.
complaints = dw_pandas["Number of Open Complaints"].astype("string").str.strip()

dw_pandas["Number of Open Complaints"] = pd.to_numeric(
    complaints.str.extract(r"^(\d+)")[0],
    errors="coerce"
).astype("Int64")

# Convert numerical columns
numeric_columns = [
    "Income",
    "Monthly Premium Auto",
    "Total Claim Amount"
]

for col in numeric_columns:
    dw_pandas[col] = pd.to_numeric(dw_pandas[col], errors="coerce")

# Convert categorical columns to consistent text values
categorical_columns = [
    "ST", "GENDER", "Education", "Policy Type", "Vehicle Class"
]

for col in categorical_columns:
    dw_pandas[col] = dw_pandas[col].astype("string").str.strip()

# Treat blank strings as missing values
dw_pandas = dw_pandas.replace(r"^\s*$", pd.NA, regex=True)

# Review the corrected data types
print(dw_pandas.dtypes)

Customer                      object
ST                            string
GENDER                        object
Education                     string
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints      Int64
Policy Type                   string
Vehicle Class                 string
Total Claim Amount           float64
dtype: object

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [5]:
rows, columns = dw_pandas.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 1071
Number of columns: 11

In [6]:
# Data types
print(dw_pandas.dtypes)

# Missing values per column
print("\nMissing values:")
print(dw_pandas.isnull().sum())

# Missing-value percentages
missing_percentage = (
    dw_pandas.isnull().mean() * 100
).round(2)

print("\nMissing-value percentage:")
print(missing_percentage.sort_values(ascending=False))

Customer                      object
ST                            string
GENDER                        object
Education                     string
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints      Int64
Policy Type                   string
Vehicle Class                 string
Total Claim Amount           float64
dtype: object

Missing values:
Customer                       0
ST                             0
GENDER                       117
Education                      0
Customer Lifetime Value        3
Income                         0
Monthly Premium Auto           0
Number of Open Complaints      0
Policy Type                    0
Vehicle Class                  0
Total Claim Amount             0
dtype: int64

Missing-value percentage:
GENDER                       10.92
Customer Lifetime Value       0.28
Total Claim Amount            0.00
Vehicle Class                 0.00
Policy Type                   0.00
Number of Open Complaints     0.00
Monthly Premium Auto          0.00
Income                        0.00
Education                     0.00
ST                            0.00
Customer                      0.00
dtype: float64

In [7]:
# Count unique values, excluding missing values
print("Unique values per column:")
print(dw_pandas.nunique())

# Display unique values for categorical columns
for col in categorical_columns:
    print(f"\n{col}:")
    print(dw_pandas[col].dropna().unique())

print(dw_pandas["GENDER"].value_counts(dropna=False))

Unique values per column:
Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       1
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

ST:
<StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali', 'AZ',
 'WA']
Length: 8, dtype: string

GENDER:
['F' 'M' 'Femal' 'Male' 'female']

Education:
<StringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Bachelors',
 'Doctor']
Length: 6, dtype: string

Policy Type:
<StringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: string

Vehicle Class:
<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car']
Length: 6, dtype: string
F         457
M         413
NaN       117
Male       39
female     28
Femal      17
Name: GENDER, dtype: int64

In [9]:
numeric_columns = [
    "Customer Lifetime Value",
    "Income",
    "Monthly Premium Auto",
    "Number of Open Complaints",
    "Total Claim Amount"
]

# Summary statistics
display(dw_pandas[numeric_columns].describe().T)

# Mean
print("\nMEAN")
print(dw_pandas[numeric_columns].mean())

# Median
print("\nMEDIAN")
print(dw_pandas[numeric_columns].median())

# Mode
print("\nMODE")
print(dw_pandas[numeric_columns].mode().iloc[0])

# Standard deviation
print("\nSTANDARD DEVIATION")
print(dw_pandas[numeric_columns].std())

# Quartiles
print("\nQUARTILES")
print(dw_pandas[numeric_columns].quantile([0.25, 0.50, 0.75]))

,count,mean,std,min,25%,50%,75%,max
Customer Lifetime Value,1068.0,7936.902593,6434.784103,2004.350700,4034.079950,5881.742350,8962.871975,58166.553500
Income,1071.0,39295.701214,30469.427060,0.000000,14072.000000,36234.000000,64631.000000,99960.000000
Monthly Premium Auto,1071.0,193.234360,1601.190369,61.000000,68.000000,83.000000,109.500000,35354.000000
Number of Open Complaints,1071.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Total Claim Amount,1071.0,404.986909,293.027260,0.382107,202.157702,354.729129,532.800000,2893.239678

MEAN
Customer Lifetime Value       7936.902593
Income                       39295.701214
Monthly Premium Auto           193.234360
Number of Open Complaints        1.000000
Total Claim Amount             404.986909
dtype: float64

MEDIAN
Customer Lifetime Value       5881.742350
Income                       36234.000000
Monthly Premium Auto            83.000000
Number of Open Complaints        1.000000
Total Claim Amount             354.729129
dtype: float64

MODE
Customer Lifetime Value      2514.59
Income                             0
Monthly Premium Auto              65
Number of Open Complaints          1
Total Claim Amount             321.6
Name: 0, dtype: object

STANDARD DEVIATION
Customer Lifetime Value       6434.784103
Income                       30469.427060
Monthly Premium Auto          1601.190369
Number of Open Complaints        0.000000
Total Claim Amount             293.027260
dtype: float64

QUARTILES
      Customer Lifetime Value   Income  Monthly Premium Auto  \
0.25              4034.079950  14072.0                  68.0
0.50              5881.742350  36234.0                  83.0
0.75              8962.871975  64631.0                 109.5

     Number of Open Complaints  Total Claim Amount
0.25                         1          202.157702
0.50                         1          354.729129
0.75                         1          532.800000

In [10]:
categorical_columns = [
    "ST",
    "GENDER",
    "Education",
    "Policy Type",
    "Vehicle Class"
]

# Count, number of unique values, most frequent value and its frequency
display(dw_pandas[categorical_columns].describe().T)

# Frequency counts and percentages
for col in categorical_columns:
    print(f"\n--- {col} ---")

    counts = dw_pandas[col].value_counts(dropna=False)

    print("Counts:")
    print(counts)

    print("\nPercentages:")
    print((counts / len(dw_pandas) * 100).round(2))

              count unique            top freq
ST             1071      8         Oregon  320
GENDER          954      5              F  457
Education      1071      6       Bachelor  324
Policy Type    1071      3  Personal Auto  780
Vehicle Class  1071      6  Four-Door Car  576

--- ST ---
Counts:
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: ST, dtype: Int64

Percentages:
Oregon        29.88
California    19.70
Arizona       17.37
Cali          11.20
Nevada         9.15
Washington     7.56
WA             2.80
AZ             2.33
Name: ST, dtype: float64

--- GENDER ---
Counts:
F         457
M         413
NaN       117
Male       39
female     28
Femal      17
Name: GENDER, dtype: int64

Percentages:
F         42.67
M         38.56
NaN       10.92
Male       3.64
female     2.61
Femal      1.59
Name: GENDER, dtype: float64

--- Education ---
Counts:
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: Education, dtype: Int64

Percentages:
Bachelor                30.25
College                 29.23
High School or Below    27.64
Master                   8.78
Doctor                   3.45
Bachelors                0.65
Name: Education, dtype: float64

--- Policy Type ---
Counts:
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: Policy Type, dtype: Int64

Percentages:
Personal Auto     72.83
Corporate Auto    21.85
Special Auto       5.32
Name: Policy Type, dtype: float64

--- Vehicle Class ---
Counts:
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: Vehicle Class, dtype: Int64

Percentages:
Four-Door Car    53.78
Two-Door Car     19.14
SUV              18.58
Sports Car        5.32
Luxury SUV        1.87
Luxury Car        1.31
Name: Vehicle Class, dtype: float64

In [12]:
print("Final dataset shape:", dw_pandas.shape)

print("\nMissing values:")
print(dw_pandas.isnull().sum())

print("\nDuplicate rows:", dw_pandas.duplicated().sum())

print("\nNumerical summary:")
display(dw_pandas[numeric_columns].describe().T)

print("\nCategorical summary:")
display(dw_pandas[categorical_columns].describe().T)

print("\nFinal data types:")
print(dw_pandas.dtypes)

Final dataset shape: (1071, 11)

Missing values:
Customer                       0
ST                             0
GENDER                       117
Education                      0
Customer Lifetime Value        3
Income                         0
Monthly Premium Auto           0
Number of Open Complaints      0
Policy Type                    0
Vehicle Class                  0
Total Claim Amount             0
dtype: int64

Duplicate rows: 0

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Customer Lifetime Value,1068.0,7936.902593,6434.784103,2004.350700,4034.079950,5881.742350,8962.871975,58166.553500
Income,1071.0,39295.701214,30469.427060,0.000000,14072.000000,36234.000000,64631.000000,99960.000000
Monthly Premium Auto,1071.0,193.234360,1601.190369,61.000000,68.000000,83.000000,109.500000,35354.000000
Number of Open Complaints,1071.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Total Claim Amount,1071.0,404.986909,293.027260,0.382107,202.157702,354.729129,532.800000,2893.239678

Categorical summary:

              count unique            top freq
ST             1071      8         Oregon  320
GENDER          954      5              F  457
Education      1071      6       Bachelor  324
Policy Type    1071      3  Personal Auto  780
Vehicle Class  1071      6  Four-Door Car  576

Final data types:
Customer                      object
ST                            string
GENDER                        object
Education                     string
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints      Int64
Policy Type                   string
Vehicle Class                 string
Total Claim Amount           float64
dtype: object